apiVersion: v1
kind: ServiceAccount
metadata:
  name: aap-controller
  namespace: aap-ee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-controller
  namespace: aap-ee
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-controller
  namespace: aap-ee
subjects:
  - kind: ServiceAccount
    name: aap-controller
    namespace: aap-ee
roleRef:
  kind: Role
  name: aap-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aap-controller-cluster
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aap-controller-cluster
subjects:
  - kind: ServiceAccount
    name: aap-controller
    namespace: aap-ee
roleRef:
  kind: ClusterRole
  name: aap-controller-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: aap-controller-token
  namespace: aap-ee
  annotations:
    kubernetes.io/service-account.name: aap-controller
type: kubernetes.io/service-account-token
