---
- name: Hello from AKS
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Show where this is running
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Python: {{ ansible_python_version }}"


    - name: Sleep for a bit to simulate work
      ansible.builtin.pause:
        seconds: 65
...
